// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudVerdict } from "./CloudVerdict";

export type CloudLookupResult = { provider: string, verdict: CloudVerdict, reason?: string, malicious?: number, suspicious?: number, harmless?: number, undetected?: number, };
