// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompromiseTarget } from "./CompromiseTarget";
import type { CompromiseTargetGroup } from "./CompromiseTargetGroup";

export type CompromiseCheckSuite = { reportOnly: boolean, groups: Array<CompromiseTargetGroup>, targets: Array<CompromiseTarget>, nextActions: Array<string>, };
