// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineStatus = { builtInYaraSources: number, externalYaraSources: number, hashIndicators: number, magikaAvailable: boolean, magikaError?: string, signatureSources: Array<string>, loadErrors: Array<string>, };
