// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanVerdict } from "./ScanVerdict";

export type Finding = { path: string, verdict: ScanVerdict, source: string, title: string, detail: string, };
