// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanVerdict } from "./ScanVerdict";

export type HashSignatureMatch = { algorithm: string, hash: string, verdict: ScanVerdict, name: string, source?: string, };
