// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PackerDetection = { detected: boolean, name: string, confidence: number, indicators: Array<string>, };
