// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanSummary = { filesSeen: number, filesScanned: number, findings: number, skipped: number, errors: number, canceled: boolean, };
