// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanOptions = { includeArchives: boolean, cloudLookup: boolean, maxFileMb: number, maxArchiveDepth: number, };
