// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { ScanFileResult } from "./ScanFileResult";
import type { ScanSummary } from "./ScanSummary";

export type ScanEvent = { "event": "scanStarted", "data": { scanId: string, targets: Array<string>, } } | { "event": "fileStarted", "data": { scanId: string, path: string, } } | { "event": "fileFinished", "data": { scanId: string, result: ScanFileResult, } } | { "event": "finding", "data": { scanId: string, finding: Finding, } } | { "event": "progress", "data": { scanId: string, filesSeen: number, filesScanned: number, findings: number, currentPath: string, } } | { "event": "scanCompleted", "data": { scanId: string, summary: ScanSummary, } } | { "event": "scanError", "data": { scanId: string, path: string | null, message: string, } };
