// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudLookupResult } from "./CloudLookupResult";
import type { ContentClassification } from "./ContentClassification";
import type { ExecutableMetadata } from "./ExecutableMetadata";
import type { HashSignatureMatch } from "./HashSignatureMatch";
import type { ScanVerdict } from "./ScanVerdict";
import type { StaticAnalysis } from "./StaticAnalysis";
import type { WindowsFileAttributes } from "./WindowsFileAttributes";

export type ScanFileResult = { path: string, size: number, sha256: string, blake3: string, verdict: ScanVerdict, yaraMatches: Array<string>, hashMatches: Array<HashSignatureMatch>, cloud: CloudLookupResult, staticAnalysis: StaticAnalysis, windowsAttributes?: WindowsFileAttributes, content?: ContentClassification, executable?: ExecutableMetadata, skippedReason?: string, error?: string, archiveDepth: number, };
