// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackerDetection } from "./PackerDetection";

export type StaticAnalysis = { entropy: number, threatScore: number, signals: Array<string>, suspiciousStrings: Array<string>, packer: PackerDetection, };
