// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowsFileAttributes = { hidden: boolean, system: boolean, reparsePoint: boolean, temporary: boolean, readonly: boolean, archive: boolean, };
